### ISSUE TITLE
Feature request: Delete backups of deleted instances automatically

### ISSUE THREAD

**Issue by Matthiator** [omniga-gmbh-co-kg/cinder-easy-backup#2]
Maybe this can be a feature request: Do you have a solution to automatically delete the backups of **deleted** instances after a certain time?

**Comment by mkuf** [comment]
Thanks for your request. 

There is already an object that contains all existing volume backups named `all_backups` which could be leveraged to find orphaned backups by searching for the contained `volume_id` and check if this volume still exists. 
If the volume isn't available anymore, we can check if the projects specific `retention` is exceeded and delete it, or add a new config attribute like `retention_orphaned` to specifiy the retention independently from the project specific `retention`

That said, I was able to add this feature to our next sprint, so this should be implemented sometime next week. 

-Markus

**Comment by mkuf** [comment]
Feature implemented with https://github.com/omniga-gmbh-co-kg/cinder-easy-backup/commit/2a0e7cdc807acbe4de9762213817c9fb8075fe83

Be sure to update your cinder-easy-backup.json to implement the new interval attributes. See https://github.com/omniga-gmbh-co-kg/cinder-easy-backup/blob/master/cinder-easy-backup.json.example for reference. 

-Markus
